model:
  context_encoder:
    input_channels: 1
    hidden_dim: 256
    num_layers: 4
    kernel_size: 3
    stride: 2
    context_dim: 512
    num_heads: 8
    dropout: 0.1

training:
  loss:
    alpha: 0.5
    beta: 0.1
    temperature: 0.07
    adaptive_weights: true
    
  optimizer:
    type: AdamW
    lr: 1e-4
    weight_decay: 0.01
    
  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 1e-6
    
  batch_size: 32
  max_epochs: 100
  early_stopping:
    patience: 10
    min_delta: 1e-4
    
  gradient_clip: 1.0
  accumulation_steps: 2

data:
  sampling_rate: 16000
  context_duration: 5.0
  mask_ratio: 0.15
  mask_length: 10
  augmentation:
    noise_types: [gaussian, pink, brown]
    snr_range: [5, 20]
    time_stretch: [0.9, 1.1]
    pitch_shift: [-2, 2]